apiVersion: v1
kind: Secret
metadata:
  name: {{ include "payment-app.fullname" . }}-db-secret
  labels:
    {{- include "payment-app.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.database.password | b64enc | quote }}