apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: spring-api
type: Opaque
data:
  
  API_KEY: {{ randAlphaNum 16 | b64enc | quote }}
  
  DB_PASSWORD: {{ randAlphaNum 24 | b64enc | quote }}