services:
  vault:
    image: hashicorp/vault:1.13.3
    container_name: local-vault
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_API_ADDR: "http://127.0.0.1:8200"
    volumes:
      - vault-data:/vault/file
      - vault-logs:/vault/logs
    cap_add:
      - IPC_LOCK
    command: server
    entrypoint: >
      sh -c '
      echo "
      storage \"file\" {
        path = \"/vault/file\"
      }
      listener \"tcp\" {
        address     = \"0.0.0.0:8200\"
        tls_disable = 1
      }
      ui = true
      " > /vault/config/local.hcl && vault server -config=/vault/config/local.hcl'

  postgres:
    image: postgres:15-alpine
    container_name: local-postgres
    environment:
      POSTGRES_USER: root_db_admin
      POSTGRES_PASSWORD: super-secret-root-password
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  application-service:
    image: node:20-alpine
    container_name: dynamic-app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_ROLE_ID
      - VAULT_SECRET_ID
    command: ["sh", "-c", "npm install axios pg uuid && node app.js"]
    depends_on:
      - vault
      - postgres

volumes:
  vault-data:
  vault-logs: