apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "finpay.fullname" . }}-api
  labels:
    {{- include "finpay.labels" . | nindent 4 }}
    app: payment-api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "finpay.selectorLabels" . | nindent 6 }}
      app: payment-api
  template:
    metadata:
      labels:
        {{- include "finpay.selectorLabels" . | nindent 8 }}
        app: payment-api
    spec:
      containers:
      - name: api
        image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: {{ include "finpay.fullname" . }}-config
              key: APP_ENV
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: {{ include "finpay.fullname" . }}-config
              key: LOG_LEVEL
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "finpay.fullname" . }}-config
              key: DB_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: {{ include "finpay.fullname" . }}-config
              key: DB_USER
        - name: PAYMENT_WORKER_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "finpay.fullname" . }}-config
              key: PAYMENT_WORKER_BASE_URL
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "finpay.fullname" . }}-db-credentials
              key: password
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          initialDelaySeconds: 20
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          initialDelaySeconds: 20
          periodSeconds: 10
        resources:
          {{- toYaml .Values.api.resources | nindent 10 }}
