apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "notification-role"
        vault.hashicorp.com/agent-inject-secret-database.conf: "secret/data/payment/config"
        vault.hashicorp.com/agent-inject-template-database.conf: |
          {{- with secret "secret/data/payment/config" -}}
          DB_USERNAME={{ .Data.data.username }}
          {{- end -}}
    spec:
      serviceAccountName: notification-sa
      containers:
        - name: application
          image: alpine:latest
          command: ["sh", "-c", "while true; do sleep 30; done"]