apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "payment-role"
        
        vault.hashicorp.com/agent-inject-secret-database.conf: "secret/data/payment/config"
        
        vault.hashicorp.com/agent-inject-template-database.conf: |
          {{- with secret "secret/data/payment/config" -}}
          DB_USERNAME={{ .Data.data.username }}
          DB_PASSWORD={{ .Data.data.password }}
          DB_HOST={{ .Data.data.host }}
          DB_PORT={{ .Data.data.port }}
          {{- end -}}
    spec:
      serviceAccountName: payment-sa
      containers:
        - name: application
          image: alpine:latest
          command: ["sh", "-c", "while true; do sleep 30; done"]