apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "payment-role"
        vault.hashicorp.com/agent-inject-secret-database.conf: "database/creds/payment-db-role"
        vault.hashicorp.com/agent-inject-template-database.conf: |
          {{- with secret "database/creds/payment-db-role" -}}
          DB_USERNAME={{ .Data.username }}
          DB_PASSWORD={{ .Data.password }}
          DB_HOST=postgresql
          DB_PORT=5432
          {{- end -}}
    spec:
      serviceAccountName: payment-sa
      containers:
        - name: application
          image: alpine:latest
          command: ["sh", "-c", "while true; do sleep 30; done"]
