# charts/spring-boot-api/values.yaml

replicaCount: 1 
spring:
  profile: default

image:
  repository: busybox
  tag: stable

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi