apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-app-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nginx-app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}