apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nginx-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  .htpasswd: "{{ required "auth.username is required" .Values.auth.username }}:{{ required "auth.password is required" .Values.auth.password }}"