apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  .htpasswd: "{{ .Values.auth.username }}:{{ required "ERROR: Password is required!" .Values.auth.password }}"