import logging

LOG_LEVEL = logging.INFO
OUTPUT_JSON_FILENAME = "anomalies_report.json"

HISTORY_WINDOW_DAYS = 14
MIN_HISTORY_DAYS = 3
MIN_ABSOLUTE_COST = 5.0  

THRESHOLD_INFO = 20.0
THRESHOLD_WARNING = 50.0
THRESHOLD_CRITICAL = 100.0