network:
  vpc_cidr: "10.20.0.0/16"
  public_subnets:
    - "10.20.1.0/24"

application:
  name: "academy-control-api"
  version: "1.3.0"

runtime:
  app_port: 8080
  database_url: "sqlite:////opt/academy-control-api/app/staging.db"

database:
  engine: "sqlite"
  storage_size: "5GB"