apiVersion: v1
kind: Service
metadata:
  name: {{ include "finpay.fullname" . }}-worker
  labels:
    {{- include "finpay.labels" . | nindent 4 }}
    app: payment-worker
spec:
  type: {{ .Values.worker.service.type }}
  ports:
  - port: {{ .Values.worker.service.port }}
    targetPort: {{ .Values.worker.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "finpay.selectorLabels" . | nindent 4 }}
    app: payment-worker
