apiVersion: v1
kind: Secret
metadata:
  name: {{ include "finpay.fullname" . }}-db-credentials
  labels:
    {{- include "finpay.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.config.dbPassword | quote }}
