api:
  replicaCount: 1
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"
  hpa:
    enabled: false

worker:
  replicaCount: 1
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
  hpa:
    enabled: false

config:
  appEnv: "development"
  logLevel: "DEBUG"

ingress:
  enabled: false

networkPolicy:
  enabled: false

secretsStore:
  keyvaultName: "kv-payment-production"