api:
  replicaCount: 3
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
worker:
  replicaCount: 2
ingress:
  enabled: true
  hosts:
    - host: api.finpay.com
      paths:
        - path: /
          pathType: Prefix