name: CD - Push to AWS ECR

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1
  ECR_REGISTRY: 834948575491.dkr.ecr.eu-central-1.amazonaws.com

permissions:
  actions: read    
  contents: read   

jobs:
  deploy-to-ecr:
    name: Deploy Images to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      - name: Find latest successful CI run ID
        id: find-run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RUN_ID=$(gh run list --branch main --status success --json databaseId,name --jq '.[] | select(.name == "CI - Build, Scan & Validate") | .databaseId' | head -n 1)
          
          if [ -z "$RUN_ID" ]; then
            echo "Error"
            exit 1
          fi
          
          
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      - name: Download API Artifact
        uses: actions/download-artifact@v4
        with:
          name: api-docker-image
          path: ./artifacts
          run-id: ${{ steps.find-run.outputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Worker Artifact
        uses: actions/download-artifact@v4
        with:
          name: worker-docker-image
          path: ./artifacts
          run-id: ${{ steps.find-run.outputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}


      - name: Load, Tag and Push API Image
        run: |
          echo "Loading API image from tarball"
          LOADED_IMAGE=$(docker load -i ./artifacts/api-image.tar | awk '/Loaded image: / {print $3}')
          
          NEW_TAG="${{ env.ECR_REGISTRY }}/$LOADED_IMAGE"
          echo "Tagging for ECR: $NEW_TAG"
          
          docker tag $LOADED_IMAGE $NEW_TAG
          docker push $NEW_TAG

      - name: Load, Tag and Push Worker Image
        run: |
          echo "Loading Worker image from tarball"
          LOADED_IMAGE=$(docker load -i ./artifacts/worker-image.tar | awk '/Loaded image: / {print $3}')
          
          NEW_TAG="${{ env.ECR_REGISTRY }}/$LOADED_IMAGE"
          echo "Tagging for ECR: $NEW_TAG"
          
          docker tag $LOADED_IMAGE $NEW_TAG
          docker push $NEW_TAG