name: Payment Platform CI (Self-Hosted)

on:
  push:
    branches:
      - main
    paths:
      - 'self_hosted_runners_part2/**'
  pull_request:
    branches:
      - main
    paths:
      - 'self_hosted_runners_part2/**'

jobs:
  build-and-test:
    runs-on: k8s-runner-set 
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.5

      - name: Build Payment API
        working-directory: ./self_hosted_runners_part2/payment-api
        run: mvn clean install 

      - name: Build Payment Worker
        working-directory: ./self_hosted_runners_part2/payment-worker
        run: mvn clean install